### ISSUE TITLE
Allow `print_tag` to be a function

### ISSUE THREAD

**Issue by garymh** [andrewferrier/debugprint.nvim#104]
I would love if I could set something like:

```
        print_tag = function ()
          table = {'💣', '🐭', '💩', '🫠', '🤡', '👻'}

          local rand = math.random(1, table.size)

          return table[rand]
        end,
```

so I'd have a random emoji in addition to the index to visually differentiate lines. I'm not sure how possible this is with the string checks here though 😅 https://github.com/andrewferrier/debugprint.nvim/blob/40fc629ffdfdcc94049bd9809e9b7992cda5fb1d/lua/debugprint/init.lua#L247

**Comment by andrewferrier** [comment]
I think it's an interesting idea, but I'm cautious about making the changes to support this without a good reason since I think it would cause issues (such as for example the deletion/commenting that you cited). Is there a good justification for this beyond having a bit of fun? (in which case I might be prepared to support an undocumented approach but with caveats).

**Comment by andrewferrier** [comment]
How would you feel about being able to override the 'counter' logic instead? I think that would achieve the same goal?

**Comment by andrewferrier** [comment]
@garymh OK, I think you should find this implemented now, on the `main` branch (not in a released version yet). See [here](https://github.com/andrewferrier/debugprint.nvim?tab=readme-ov-file#customizing-counter-logic) for how to use.

Something like this should probably work in your case:

```lua
print_tag = function ()
  table = {'💣', '🐭', '💩', '🫠', '🤡', '👻'}

  local rand = math.random(1, table.size)

  return '[' .. table[rand] .. ']'
end

debugprint.setup({ display_counter = print_tag })
```

Please test it out and let me know! Hope you find that helpful.
