### ISSUE TITLE
How to remove the filename+linenumber?

### ISSUE THREAD

**Issue by ariel-frischer** [andrewferrier/debugprint.nvim#122]
Hey really want to just remove the `filename:linenumber` from my print statements but I'm not sure if there is an option for that?

I've tried messing with all of these options to no avail:
```
    opts = {
      -- remove the DEBUGPRINT tag
      print_tag = "",
      display_counter = false,
      display_snippet = false,
      filetypes = {
        python = {
          left = 'print(f"',
          left_var = 'print(f"',
          mid_var = '{',
          right_var = '}"',
          right = '")',
        },
      },
    },
```

I still get something like this: 
```
    configuration = Configuration.from_runnable_config(config)
    print(f": tools.py:35: configuration={configuration}")
```
But I want this: 
```
    print(f"configuration={configuration}")
```
How?

**Comment by andrewferrier** [comment]
There's currently no built in way to do this, but I can consider adding something. To help me understand the right way to do it: what's your motivation here? Why do you want to remove the filename/line number? Is this true for every debug line you want to implement? What about non-variable debug lines? Do you use those?

**Comment by ariel-frischer** [comment]
The logs just feel a bit cluttered, and when I'm making multiple edits the line numbers keep changing. I know the file most of the time. I mostly (like 95%) of the time am using this plugin with variable debug lines. I would assume if it is a non-variable debug line it would be more useful to keep the file:linenumber syntax.

**Comment by andrewferrier** [comment]
Hmm ok, fair, I can see that. Let me think about the right way to make that configurable, I'm definitely open to that.

**Comment by andrewferrier** [comment]
I think I'm going to implement this in two pieces:

- [ ] Allow `print_tag` to be set to `""` or `nil`, which will disable the additional `: `. If this is done, I want to issue some kind of warning when running `DeleteDebugPrints` or `CommentDebugPrints`, since there is no way for it to operate.
- [ ] Add options called `display_filename` and `display_linenumber`, both of which default to true. If set to false they remove the relevant sections. If all `display_*` options are set to false, as well as `print_tag`, so that a plain debug line is about to emit effectively an empty output, `display_filename` will effectively be forced to `true` for that line. This will not be true for 'variable' lines.

**Comment by andrewferrier** [comment]
Hi - you should now find the option `display_location` added to the version on the `main` branch. If you set up `debugprint` with `print_tag = "", display_location = false, display_counter = false, display_snippet = false`, I think the variable debug print will now do what you were originally looking for!

Please let me know how this works for you and if you spot any issues.

**Comment by ariel-frischer** [comment]
Awesome its working great on my end! Thanks for implementing so quickly its a great plugin.

**Comment by andrewferrier** [comment]
Excellent, that's great, thanks for the quick feedback.
