### ISSUE TITLE
nvim_buf_set_lines  got E565: Not allowed to change text or change window

### ISSUE THREAD

**Issue by thenewvu** [andrewferrier/debugprint.nvim#153]
I got the below error that I think it relates to a recent commit:
3ad3f7372ff6241a20f5f4f931d989d07bf3883f

```
E5108: Error executing lua .../plugged/debugprint.nvim/lua/debugprint/utils/buffer.lua:46: E565: Not allowed to change text or change window
stack traceback:
        [C]: in function 'nvim_buf_set_lines'
        .../plugged/debugprint.nvim/lua/debugprint/utils/buffer.lua:46: in function 'insert_and_indent_line'
        ...fig/nvim/plugged/debugprint.nvim/lua/debugprint/init.lua:238: in function 'handle_debugprint_line'
        ...fig/nvim/plugged/debugprint.nvim/lua/debugprint/init.lua:250: in function <...fig/nvim/plugged/debugprint.nvim/lua/debugprint/init.lua:249>
        [C]: in function 'nvim_feedkeys'
        ...fig/nvim/plugged/debugprint.nvim/lua/debugprint/init.lua:269: in function 'debugprint_insertkeys'
        ...fig/nvim/plugged/debugprint.nvim/lua/debugprint/init.lua:319: in function <...fig/nvim/plugged/debugprint.nvim/lua/debugprint/init.lua:276>
```

My neovim version:
```
NVIM v0.10.3
Build type: Release
LuaJIT 2.1.1734355927
```

**Comment by andrewferrier** [comment]
Thanks. I'll take a look. Do you have any recreation instructions? What were you doing when this error popped up?

**Comment by thenewvu** [comment]
I found out this causes the error (but don't know why):
```
vim.keymap.set({"n", "v"}, "<Leader>d", function() return require('debugprint').debugprint({ignore_treesitter = false, variable = true}) end, {expr = true})
```

This doesn't cause the error:
```
vim.keymap.set({"n", "v"}, "<Leader>d",  require('debugprint').debugprint)
```

This doesn't cause the error too:
```
" nnoremap <leader>d <cmd>lua require('debugprint').debugprint({ignore_treesitter = false, variable = true})<cr>
" vnoremap <leader>d <cmd>lua require('debugprint').debugprint({ignore_treesitter = false, variable = true})<cr>
```

**Comment by andrewferrier** [comment]
OK, thanks for the more detailed description. I see and can recreate the issue you are describing.

However, in general, I have not supported mapping to the `debugprint()` function directly [since version 2.0.0](https://github.com/andrewferrier/debugprint.nvim?tab=readme-ov-file#mapping-deprecation). In my experience `expr = true` causes a lot of issues, and folks were mapping keys inconsistently, so I decided to instead move to a model adopted by some plugins of doing the mapping for the user. The new approach is to use the [configurable mapping approach](https://github.com/andrewferrier/debugprint.nvim?tab=readme-ov-file#keymappings-and-commands).

What you are trying to achieve is possible with the (customizable) out-of-the-box `variable_below` (normal mode) and `variable_below` (visual mode) keymappings, like this:

```
 keymaps = {
            normal = {
                variable_below = "<Leader>d",
            },
            visual = {
                variable_below = "<Leader>d",
            },
        },
```

Unless there's a compelling reason otherwise, therefore, I'm tempted not to fix this. Is there a reason this won't work for you?

**Comment by thenewvu** [comment]
Thank you for the information, I didn't follow the updates, I have read the latest document and saw the new way to setup keymaps. Sorry for taking your time.

**Comment by andrewferrier** [comment]
No problem, obviously I needed to communicate this better! Thanks for taking the time to open the issue, do let me know if this method doesn't work for you for some reason.
