### ISSUE TITLE
[Feature request] Optional counter

### ISSUE THREAD

**Issue by goingtosleep** [andrewferrier/debugprint.nvim#32]
Hi, it's great if you can add an option to disable the `counter`. Because the counter is not reset after deleting all debugprints. Also if I insert debugprints for different variables in the same line, the order of numbers will be reversed, e.g.:

```python
def f(x):
    a = 2*x
    print(f"DEBUG[2]: new.py:93: x={x}")
    print(f"DEBUG[1]: new.py:93: a={a}")
    return a
```

No big deal but it looks a bit weird I think. It would be more natural if the numbers are not shown.
Thank you for a very nice plugin 😊

**Comment by andrewferrier** [comment]
@goingtosleep interesting. Thanks for your thoughts. From my perspective, the counter is simply a unique identifier that's tracked in each NeoVim session (we don't persist it between sessions) - so it's to help you correlate lines. The actual sequence in my mind wasn't that important, which is why I don't reset it (we don't track which lines are added/deleted).

Is there a particular reason other than 'neatness'? I think I'd be happy to provide a simple toggle or other way to override the message, but more sophisticated logic for the counter I think would be overly complex.

**Comment by andrewferrier** [comment]
OK, I've added this, there's now a new option `display_counter`. It defaults to true so you'd have to explicitly turn it off:

```lua
require("debugprint").setup({ display_counter = false })
```

I think this addresses what you were after?

**Comment by goingtosleep** [comment]
Yes @andrewferrier, thank you so much for the quick update 🤩

**Comment by andrewferrier** [comment]
You're welcome :)
