### ISSUE TITLE
Python and sys.stderr

### ISSUE THREAD

**Issue by mgabs** [andrewferrier/debugprint.nvim#58]
While working on python, I typically don't use `sys`.
now if I want to use the plugin, I need to import `sys` and clean it lateron.
Is there a reason to keep it ?
Why not remove `file=sys.stderr` ?

**Comment by andrewferrier** [comment]
@mgabs the intention was to ensure that debugging is ending up on stderr rather than stdout (see https://github.com/andrewferrier/debugprint.nvim/issues/48).

If you're very keen to not to do this, you can overwrite the opts when setting up debugprint, for example:

    require('debugprint').setup({
        filetypes = {
            ["python"] = {
                left = 'print(f"',
                right = '")',
                mid_var = "{",
                right_var = '}")',
            },
        },
    })

Any suggestions on how to handle this better out-of-the-box for folks like yourself who prefer doing it this way are welcome...

**Comment by mgabs** [comment]
Thank you.
I think it's enough to expose the config to create custom behavior

**Comment by andrewferrier** [comment]
FYI - this default has now been changed on the `main` branch not to use stderr for Python.
