### ISSUE TITLE
Confusing mismatch between version and public README

### ISSUE THREAD

**Issue by carlosflorencio** [andrewferrier/debugprint.nvim#96]
Hi!

I've updated the plugin to the latest version and when migrating the keybindings for the new settings they don't seem to be applied.

Example config:
```lua
  {
    'andrewferrier/debugprint.nvim',
    dependencies = {
      'echasnovski/mini.nvim', -- Needed to enable :ToggleCommentDebugPrints for NeoVim <= 0.9
      'nvim-treesitter/nvim-treesitter', -- Needed to enable treesitter for NeoVim 0.8
    },
    version = '*',
    opts = {
      keymaps = {
        normal = {
          plain_below = '<leader>dd', -- not working
        },
      },
    },
  },
```

The custom keymap I'm trying to set `<leader>dd` doesn't work, the default keybinding works `g?p`.

**Comment by andrewferrier** [comment]
@carlosflorencio thanks for bringing this to my attention. I think I see the issue. You are using the released version of `debugprint.nvim` with `version = '*'`, and that does not yet include the change - it has not been merged in. This is technically 'correct', but I would agree that it's confusing, since the public README does mention this change.

I'll try and think about a better way to handle this. In the meantime, you can 'fix' this by either reverting back to the old way of handling keybindings (this will work until I release these changes, which will happen in the next few weeks), or upgrade to the development version by removing `version = '*'`.

**Comment by carlosflorencio** [comment]
Works now 😃 .

Thanks for the update.

**Comment by andrewferrier** [comment]
Thanks for confirming :) I'm going to re-open this because I'm going to use it as a way to figure out how to handle the mismatching README better in the future.

**Comment by andrewferrier** [comment]
On reflection, I don't think there's a meaningful way to address this. The README is correct and consistent with the code, it's simply that the README shown when looking at the default GitHub page is the one from the `main` branch, not the latest release. This is the standard way GitHub works and is also consistent with the `release-please` action I'm using to manage releases. The auto-generated NeoVim documentation is correct and consistent with the release being used. Whilst it's not ideal, I can't think of a better way to handle it than the current way without adding a lot of complexity. It's unlikely to happen often since in general I'm trying to keep changes backward-compatible anyway.

I'm going to close this issue. Thanks for bringing it to my attention. Glad we fixed the main issue for you.
